# PostgreSQL (Railway)
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.h2.console.enabled=false

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.sql.init.data-locations=classpath:data-postgresql.sql
